### ISSUE TITLE
Will be backport to 1.20.1?

### ISSUE THREAD

**Issue by F-708** [absolutelyaya/Formidulus#1]
It would be really cool to see this mod on older version, maybe + sinytra connector

**Comment by absolutelyaya** [comment]
I have decided against back porting it since I'd need to rewrite some substantial parts of the mod, like networking code and everything handled by Item Components; which makes a back port pretty difficult, or at least time consuming
even if I took the time and back-ported it, maintaining it would be really difficult as well
sorry- I hope you understand

**Comment by F-708** [comment]
> I have decided against back porting it since I'd need to rewrite some substantial parts of the mod, like networking code and everything handled by Item Components; which makes a back port pretty difficult, or at least time consuming even if I took the time and back-ported it, maintaining it would be really difficult as well sorry- I hope you understand

Its fine. Mod is very well made. Good animations, some type of cutscenes, interesting fight. It may be very hard to port on version, which got less functionality than newest versions of fabric loader.
Wish ya good luck in next updates!
